language: node_js
node_js:
- '0.11'
before_script:
- npm install -g grunt-cli
- git submodule update --init --recursive
script:
#- grunt release
#- browserstack-runner init
- grunt test --saucelabs
env:
  global:
    - SAUCE_USERNAME=banguero
    - SAUCE_ACCESS_KEY=3d3d6a1f-4e0a-48f7-b625-ae5afb8e477a
